const sceneImage=()=>document.getElementById("sceneImage");const bottomBar=()=>document.getElementById("bottomBar");
async function initApp(){appState.adventures=window.ADVENTURE_DATA||{};await loadUsers();await loadQuestions();renderStart();}
async function loadUsers(){try{const r=await fetch(APP_CONFIG.PATHS.USERS_JSON);appState.users=await r.json();}catch(e){console.warn("No se pudo cargar usuarios.json. Se usará lista vacía.",e);appState.users=[];}}
async function loadQuestions(){const r=await fetch(APP_CONFIG.PATHS.QUESTIONS_CSV);const text=await r.text();appState.questions=parseCSV(text).map(cleanQuestionRow);}
function setSceneImage(src){sceneImage().style.opacity="0";setTimeout(()=>{sceneImage().src=src;sceneImage().onload=()=>{sceneImage().style.opacity="1";}},120);}
function setButtons(buttons){bottomBar().innerHTML="";buttons.forEach(btn=>{const el=document.createElement("button");el.textContent=btn.text;el.className=btn.className||"";el.disabled=!!btn.disabled;el.addEventListener("click",btn.onClick);bottomBar().appendChild(el);});}
function hideAllPanels(){["startPanel","quizPanel","feedbackPanel","finalPanel"].forEach(id=>document.getElementById(id).classList.add("hidden"));}
function renderStart(){appState.currentScreen="START";hideAllPanels();setSceneImage("./BASE/V1.jpg");document.getElementById("startPanel").classList.remove("hidden");setButtons([{text:"ACTIVAR MÚSICA",className:"warning",onClick:playIntroAudio}]);setupUserSearch();}
function playIntroAudio(){const audio=document.getElementById("introAudio");audio.volume=.35;audio.play().catch(err=>console.warn("Audio bloqueado por navegador:",err));}
function stopIntroAudio(){const audio=document.getElementById("introAudio");audio.pause();audio.currentTime=0;}
function renderMap(){stopIntroAudio();appState.currentScreen="MAP";hideAllPanels();setSceneImage("./BASE/V2.jpg");const adventureButtons=Object.values(appState.adventures).filter(a=>a.ready).map(a=>({text:a.label,className:"success",onClick:()=>startAdventure(a.key)}));setButtons([...adventureButtons,{text:"PICKING ELECTRO MENOR",className:"secondary",disabled:true},{text:"ALMACENAMIENTO",className:"secondary",disabled:true}]);}
function startAdventure(key){appState.currentAdventureKey=key;appState.currentSceneIndex=0;renderAdventureScene();}
function renderAdventureScene(){hideAllPanels();const adv=appState.adventures[appState.currentAdventureKey];const scene=adv.scenes[appState.currentSceneIndex];setSceneImage(scene.bg);const isFirst=appState.currentSceneIndex===0;const isLast=appState.currentSceneIndex===adv.scenes.length-1;if(isLast){setButtons([{text:"RESOLVER CUESTIONARIO",className:"success",onClick:openQuiz},{text:"CAMBIAR AVENTURA",className:"secondary",onClick:renderMap}]);return;}setButtons([{text:"ATRÁS",className:"secondary",onClick:()=>{if(isFirst)renderMap();else{appState.currentSceneIndex--;renderAdventureScene();}}},{text:"SIGUIENTE",className:"success",onClick:()=>{appState.currentSceneIndex++;renderAdventureScene();}}]);}
function renderFinal(){hideAllPanels();setSceneImage("./BASE/V20.jpg");const grade=calculateGrade();const level=getResultLevel(grade);const panel=document.getElementById("finalPanel");panel.innerHTML=`<h1>🏆 RESULTADOS FINALES</h1><div class="result-line"><strong>Nombre:</strong> ${appState.selectedUser?.nombre_completo||""}</div><div class="result-line"><strong>Aventura:</strong> ${appState.adventures[appState.currentAdventureKey]?.label||appState.currentAdventureKey}</div><div class="result-line"><strong>Respuestas correctas:</strong> ${appState.quiz.score} de 5</div><div class="result-line"><strong>Nota:</strong> <span class="yellow">${grade} / 20</span></div><div class="result-line"><strong>Nivel:</strong> ${level}</div><hr><button class="success" onclick="sendAndFinish()">GUARDAR RESULTADO</button>`;panel.classList.remove("hidden");setButtons([{text:"NUEVA AVENTURA",className:"secondary",onClick:renderMap},{text:"FINALIZAR",className:"success",onClick:renderStart}]);}
async function sendAndFinish(){const payload=buildResultPayload();const result=await sendResultToBackend(payload);alert(result.status==="mock"?"Resultado simulado en consola.":"Resultado enviado.");}
